# 日本語のコメント許すやつ
Style/AsciiComments:
    Enabled: false

# frozen_string_literal: trueはなくていい
Style/FrozenStringLiteralComment:
    Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
    Enabled: false